apiVersion: v1
kind: Pod
metadata:
  name: oscal-web-pd
  labels:
    app: oscal-web
    version: v1.0
spec:
  containers:
  - name: oscal-web
    image: oscal/demo:1.0
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pd
  labels:
    app: redis
    role: master
    tier: backend
spec:
  containers:
  - name: master
    image: redis:alpine
    ports:
    - containerPort: 6379
