apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: oscal-web-rs
  labels:
    app: oscal-web
    version: v1.0
spec:
  replicas: 5
  selector:
    matchLabels:
      app: oscal-web
  template:
    metadata:
      name: oscal-web
      labels:
        app: oscal-web
        version: v1.0
    spec:
      containers:
      - name: oscal-web
        image: oscal/demo:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:alpine
        ports:
        - containerPort: 6379
